<template>
  <div class="container">
    <div class="scene">
        <div class="face slide-top">face 1</div>
        <div class="face slide-top">face 2</div>
        <div class="face slide-top">face 3</div>
    </div>
  </div>
</template>

<script>
import carline from "./carline.vue";
export default {
  name: "carousel2",
  components: {
    carline
  },
  props: {},
  data() {
    return {
      txt_array: [
        { txt: "text1", poz: 0 },
        { txt: "text2", poz: 0 },
        { txt: "text3", poz: 0 },
        { txt: "text4", poz: 0 },
        { txt: "text5", poz: 0 },
        { txt: "text6", poz: 0 },
        { txt: "text7", poz: 0 },
        { txt: "text8", poz: 0 },
        { txt: "text9", poz: 0 }
      ]
    };
  },
  mounted() {

  },
  methods: {
 changeSide() {
}
  }
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.face {
  width: 100px;
  border:1px solid;
  animation-name: example;
  animation-duration: 5s;
  animation-iteration-count: infinite;
}

.slide-top {
	        animation: slide-top 1s cubic-bezier(0.150, 0.350, 0.550, 0.750) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2019-8-5 13:51:1
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/* ----------------------------------------------
 * Generated by Animista on 2019-8-5 13:51:21
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-top
 * ----------------------------------------
 */
@keyframes slide-top {
  0% {
     transform: rotate(0deg) translate(0px,0px);
  }
  100% {
     transform: rotate(0deg) translate(0px,-20px);
  }
}

</style>
